<script>
    require(['jquery', 'mage/gallery/gallery', 'wpProductLabels'], function($, gallery){
        $('[data-gallery-role=gallery-placeholder]').on('gallery:loaded', function () {
            var requestUrl = '<?php echo $this->getUrl("wpproductlabels/product/labels/product_id/" . $this->getProduct()->getId()); ?>';
            $.get({
                url: requestUrl,
                cache: false
            }, function(result) {
                var labelData = JSON.parse(result);
                if(labelData.imagePosition)
                    $('.fotorama__stage').append(labelData.imagePosition);
                if(labelData.otherPosition)
                    $('.product-info-main').append(labelData.otherPosition);
            });

            $(this).on('fotorama:ready', function() {
                var fotoramaStageLeft = parseInt($('.fotorama__stage').css('left'));
                if (fotoramaStageLeft) {
                    $('.fotorama__stage').width($('.fotorama__stage').width() - fotoramaStageLeft);
                }
            });
        });
    });
</script>