<?php
// @codingStandardsIgnoreFile
/** @var \WeltPixel\AdvancedWishlist\Block\Customer\Collections $block */
$wishlists = $block->getWishlistsForCustomer();
$imageBlock = $block->getLayout()->getBlock('customer.multiple.wishlist.item.image');
$imagesLimit = 6;
?>
<div class="multiple-wishlist-container">
<?php
if (count($wishlists)) :
foreach ($wishlists as $wishlist) :
    $wishlistName = $wishlist->getWishlistName();
    $shareCode = $wishlist->getSharingCode();
    $itemsNr = count($wishlist->getItemCollection());
    $items = $wishlist->getItemCollection()->clear()->setPageSize($imagesLimit)->setCurPage(1)->setOrder('added_at');
    $wishListImages = [];
    foreach ($items as $item) {
        $wishListImages[] =  $imageBlock->setItem($item)->toHtml();
    }
?>
<a class="multiple-wishlist-element" href="<?= $block->getUrl('wp_collection/share/' . $shareCode, ['_secure' =>  true])?>">
    <div class="multiple-wishlist-box-wrapper">
        <?php for ($i = 0; $i< $imagesLimit; $i++) : ?>
            <?php $image = isset($wishListImages[$i]) ? $wishListImages[$i] : '' ?>
            <div class="box"><?= $image ?></div>
        <?php endfor; ?>
        <div class="box-bottom">
            <div class="wishlist-title"><?= $wishlist->getWishlistName(); ?></div>
            <div class="wishlist-items"><?= __('%1 items', $itemsNr); ?></div>
        </div>
    </div>
</a>
<?php endforeach; ?>
<?php else: ?>
<p class="no-collection"><?= __('There are no collections available.') ?></p>
<?php endif; ?>
</div>
